name: Update Readme

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Get current date for commit message
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Generate new Readme
        env:
          WeatherAPIKey: ${{ secrets.WEATHER_API }}
          GithubToken: ${{ secrets.GITHUB_TOKEN }}
        run: bun run index.ts

      - name: Commit Files
        env:
          DATE: ${{ env.DATE }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "bot update: ${{ env.DATE }}" -a

      - name: Push changes back to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
